kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: enterprisecoding-nfs
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: enterprisecoding.com/nfs
mountOptions:
  - vers=4.1